### ISSUE TITLE
我使用了您的代码，但是在我的局域网环境下，速度太慢了

### ISSUE THREAD

**Issue by suyang-fengzi** [tkzcfc/net_uv_new#1]
在局域网下，网速只能达到1.5M ，可否给我个联系方式，请教您

**Comment by tkzcfc** [comment]
老哥怎么玩的啊，我测了十多兆一秒呀

**Comment by suyang-fengzi** [comment]
大哥，太好了，您终于回复了，加个wq或者微信吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tkzcfc <notifications@github.com&gt;
发送时间: 2020年9月24日 21:34
收件人: tkzcfc/net_uv_new <net_uv_new@noreply.github.com&gt;
抄送: suyang-fengzi <suyang@54nb.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tkzcfc/net_uv_new] 我使用了您的代码，但是在我的局域网环境下，速度太慢了 (#1)





 
老哥怎么玩的啊，我测了十多兆一秒呀

**Comment by suyang-fengzi** [comment]
留个电话？我真的需要很好好好沟通一下的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tkzcfc <notifications@github.com&gt;
发送时间: 2020年9月24日 21:34
收件人: tkzcfc/net_uv_new <net_uv_new@noreply.github.com&gt;
抄送: suyang-fengzi <suyang@54nb.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tkzcfc/net_uv_new] 我使用了您的代码，但是在我的局域网环境下，速度太慢了 (#1)





 
老哥怎么玩的啊，我测了十多兆一秒呀

**Comment by tkzcfc** [comment]
好的  加我QQ吧  2426898730
